//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETDAC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ETDB1Entities : DbContext
    {
        public ETDB1Entities()
            : base("name=ETDB1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table1> Table1 { get; set; }
        public virtual DbSet<RGD_Merchant> RGD_Merchant { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<RGD_Transaction> RGD_Transaction { get; set; }
        public virtual DbSet<RGD_Account> RGD_Account { get; set; }
    
        public virtual ObjectResult<getData_Result> getData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getData_Result>("getData");
        }
    
        public virtual ObjectResult<sp_getMerchantBoard_Result1> sp_getMerchantBoard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getMerchantBoard_Result1>("sp_getMerchantBoard");
        }
    
        public virtual ObjectResult<sp_getTransactionBoard_Result> sp_getTransactionBoard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getTransactionBoard_Result>("sp_getTransactionBoard");
        }
    }
}
