//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETDAC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RGD_Transaction
    {
        public int id { get; set; }
        public string merchantname { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> userpayamount { get; set; }
        public Nullable<decimal> companypayamount { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> changedate { get; set; }
        public string useremail { get; set; }
        public string status { get; set; }
    }
}
