//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETDAC.Model
{
    using System;
    
    public partial class sp_getMerchantBoard_Result1
    {
        public string Merchant { get; set; }
        public decimal Amount { get; set; }
    }
}
